image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start containers
    command: |
      docker-compose up -d
      gp sync-done containers 
  - name: Change ownership of themes and plugins directory
    command: |
      gp sync-await containers # Wait for the container task
      sudo chown gitpod:gitpod ./mythemes/.
      sudo chown gitpod:gitpod ./myplugins/.
ports:
  - name: Web App
    port: 8080
    onOpen: open-preview
    visibility: private
