image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start containers
    command: |
      docker-compose up -d

ports:
  - name: Web App
    port: 8080
    onOpen: open-preview
    visibility: private
