image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start containers
    command: |
      docker-compose up -d
      chown gitpod:gitpod ./mythemes/.
      chown gitpod:gitpod ./myplugins/.
ports:
  - name: Web App
    port: 8080
    onOpen: open-preview
    visibility: private
