tasks:
  - name: Start containers (Wordpress and MariaDB)
    init: |
      docker-compose up -d

  - name: Wait for WP to be ready
    command: |
      gp ports await 8080

ports:
  - name: Web App
    port: 8080
    onOpen: open-preview
    visibility: private
